project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "The Mode Shift"
  site-url: "https://themodeshift.scot"
  navbar:
    background: primary
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: theme.scss
    css: styles.css